//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _005_ConsumidorWCFDados.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Filho))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Pessoa))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Filho))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Pessoa))]
    public partial class EntityObject : _005_ConsumidorWCFDados.Proxy.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _005_ConsumidorWCFDados.Proxy.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _005_ConsumidorWCFDados.Proxy.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filho", Namespace="http://schemas.datacontract.org/2004/07/_004_WCFDados", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Filho : _005_ConsumidorWCFDados.Proxy.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoPessoaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _005_ConsumidorWCFDados.Proxy.Pessoa PESSOAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _005_ConsumidorWCFDados.Proxy.EntityReferenceOfPessoaKPTsWPEk PESSOAReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoPessoa {
            get {
                return this.CodigoPessoaField;
            }
            set {
                if ((this.CodigoPessoaField.Equals(value) != true)) {
                    this.CodigoPessoaField = value;
                    this.RaisePropertyChanged("CodigoPessoa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _005_ConsumidorWCFDados.Proxy.Pessoa PESSOA {
            get {
                return this.PESSOAField;
            }
            set {
                if ((object.ReferenceEquals(this.PESSOAField, value) != true)) {
                    this.PESSOAField = value;
                    this.RaisePropertyChanged("PESSOA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _005_ConsumidorWCFDados.Proxy.EntityReferenceOfPessoaKPTsWPEk PESSOAReference {
            get {
                return this.PESSOAReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PESSOAReferenceField, value) != true)) {
                    this.PESSOAReferenceField = value;
                    this.RaisePropertyChanged("PESSOAReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://schemas.datacontract.org/2004/07/_004_WCFDados", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Pessoa : _005_ConsumidorWCFDados.Proxy.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _005_ConsumidorWCFDados.Proxy.Filho[] FILHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _005_ConsumidorWCFDados.Proxy.Filho[] FILHO {
            get {
                return this.FILHOField;
            }
            set {
                if ((object.ReferenceEquals(this.FILHOField, value) != true)) {
                    this.FILHOField = value;
                    this.RaisePropertyChanged("FILHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _005_ConsumidorWCFDados.Proxy.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _005_ConsumidorWCFDados.Proxy.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityReferenceOfPessoaKPTsWPEk))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Pessoa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Filho[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Filho))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.Pessoa[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfPessoaKPTsWPEk", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfPessoaKPTsWPEk : _005_ConsumidorWCFDados.Proxy.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityReferenceOfPessoaKPTsWPEk))]
    public partial class EntityReference : _005_ConsumidorWCFDados.Proxy.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _005_ConsumidorWCFDados.Proxy.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _005_ConsumidorWCFDados.Proxy.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_005_ConsumidorWCFDados.Proxy.EntityReferenceOfPessoaKPTsWPEk))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IPessoaService")]
    public interface IPessoaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPessoaService/Get", ReplyAction="http://tempuri.org/IPessoaService/GetResponse")]
        _005_ConsumidorWCFDados.Proxy.Pessoa Get(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPessoaService/GetAll", ReplyAction="http://tempuri.org/IPessoaService/GetAllResponse")]
        _005_ConsumidorWCFDados.Proxy.Pessoa[] GetAll();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPessoaServiceChannel : _005_ConsumidorWCFDados.Proxy.IPessoaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PessoaServiceClient : System.ServiceModel.ClientBase<_005_ConsumidorWCFDados.Proxy.IPessoaService>, _005_ConsumidorWCFDados.Proxy.IPessoaService {
        
        public PessoaServiceClient() {
        }
        
        public PessoaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PessoaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PessoaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _005_ConsumidorWCFDados.Proxy.Pessoa Get(int codigo) {
            return base.Channel.Get(codigo);
        }
        
        public _005_ConsumidorWCFDados.Proxy.Pessoa[] GetAll() {
            return base.Channel.GetAll();
        }
    }
}
